configuration:
    authenticationConfiguration:
        password: "rambo"
    serverConfiguration:
        # type can be OPEN_URL or FORCED_URL or FORCED_URL_NO_PASSWORD - later two need proxiedUrl uncommented
        type: "FORCED_URL_NO_PASSWORD"
        listenHost: "localhost"
        port: "1111"
        requestsPerConnection: "10000"
        proxiedUrl: "ws://localhost:8081/borderconnect/api/sockets/borderconnect"